# Generated by Django 5.2.9 on 2026-04-04 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="email",
            field=models.EmailField(
                default="test@example.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="partner",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
