# Generated by Django 5.2.9 on 2026-04-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_partner_email_alter_partner_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="is_trial",
            field=models.BooleanField(default=False, verbose_name="Période d'essai"),
        ),
        migrations.AddField(
            model_name="partner",
            name="trial_end",
            field=models.DateField(blank=True, null=True, verbose_name="Fin du trial"),
        ),
        migrations.AddField(
            model_name="partner",
            name="trial_notified",
            field=models.BooleanField(
                default=False, verbose_name="Email expiration envoyé"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="trial_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Début du trial"
            ),
        ),
        migrations.AlterField(
            model_name="adminnotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("unpaid_subscription", "Abonnement impayé"),
                    ("unpaid_ad", "Publicité impayée"),
                    ("email_change", "Changement email en attente"),
                    ("new_partner", "Nouveau partenaire"),
                    ("trial_expired", "Trial expiré"),
                ],
                max_length=30,
            ),
        ),
    ]
