# Generated by Django 5.2.9 on 2026-04-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_partner_is_trial_partner_trial_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("active", "Paiement actif"),
                    ("not_active", "Paiement non actif"),
                ],
                default="not_active",
                max_length=20,
                verbose_name="Statut paiement",
            ),
        ),
    ]
