# Generated by Django 5.2.9 on 2026-04-06 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_partner_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnereventmedia",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="partnerad",
            name="price_per_day",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
