# Generated by Django 5.2.9 on 2026-04-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0005_partnereventmedia_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerevent",
            name="boost_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partnerevent",
            name="boost_payment_ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partnerevent",
            name="boosted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
