# Generated by Django 5.2.9 on 2026-04-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0006_partnerevent_boost_paid_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Compteur Reçus",
            },
        ),
    ]
