# Generated by Django 5.2.9 on 2026-04-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0007_receiptcounter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receiptcounter",
            options={"verbose_name": "Compteur de reçus"},
        ),
    ]
