# Generated by Django 5.2.9 on 2026-04-09 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0008_alter_receiptcounter_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReceiptCounter",
            new_name="Receipt",
        ),
        migrations.CreateModel(
            name="ReceiptHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=20, unique=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Abonnement"),
                            ("boost", "Boost Événement"),
                            ("ad", "Publicité"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("client_code", models.CharField(blank=True, max_length=20)),
                ("payment_ref", models.CharField(blank=True, max_length=255)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("sent_to_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reçu",
                "verbose_name_plural": "Reçus",
                "ordering": ["-created_at"],
            },
        ),
    ]
