# Generated by Django 5.2.9 on 2026-04-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0009_rename_receiptcounter_receipt_receipthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipthistory",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
