# Generated by Django 5.2.9 on 2026-04-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0010_receipthistory_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipthistory",
            name="email_change_token",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
