# Generated by Django 5.2.9 on 2026-04-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0011_receipthistory_email_change_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipthistory",
            name="email_change_token",
        ),
        migrations.AddField(
            model_name="partner",
            name="email_change_token",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="partner",
            name="new_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
