# Generated by Django 5.2.9 on 2026-04-05 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0003_userpreference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={
                "verbose_name": "Paramètres de prix",
                "verbose_name_plural": "Paramètres de prix",
            },
        ),
        migrations.CreateModel(
            name="PricingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boost_price_per_day",
                    models.DecimalField(
                        decimal_places=3,
                        default=5.0,
                        help_text="Prix facturé par jour pour booster un événement partenaire.",
                        max_digits=8,
                        verbose_name="Prix boost événement (TND/jour)",
                    ),
                ),
                (
                    "ad_price_per_day",
                    models.DecimalField(
                        decimal_places=3,
                        default=3.0,
                        help_text="Prix facturé par jour pour une publicité partenaire.",
                        max_digits=8,
                        verbose_name="Prix publicité (TND/jour)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pricing_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres de prix",
                "verbose_name_plural": "Paramètres de prix",
            },
        ),
    ]
